### ISSUE TITLE
Framework not running on apple m1 arm64 simulator.

### ISSUE THREAD

**Issue by alyfreym** [alibaba/CicadaPlayer#736]
I noticed that if you delete all values from Other Linker Flags in alivcffmpeg then it is works. Can you fix that please? 
<img width="969" alt="Screenshot 2023-12-30 at 15 41 15" src="https://github.com/alibaba/CicadaPlayer/assets/29518174/c67bc10f-2e8c-4c7c-80d4-197860f3a1da">

It is very important. Because if I use this framework in my project I can't use tools like Address sanitiser because this tool works only on simulator.

It is very strange why your framework not running on arm64 simulator because simulator have the same arch as physical  device now with m chips.

**Comment by pingkai** [comment]
Sorry about that, this project hasn't supported the arm64 simulator, because if you want to support the arm64 simulator, the framework should be in the format of XCFramework. The former format can't contain two arm64 arch libraries. If you want to support that, you should change the format of all the frameworks to XCFramework.

https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle
